apiVersion: skaffold/v3
kind: Config
metadata:
  name: cloud-run-app
profiles:
  - name: prev
    manifests:
      rawYaml:
        - cloudrun-mnt-prev.yaml
  - name: crr
    manifests:
      rawYaml:
        - cloudrun-mnt.yaml
deploy:
  cloudrun: {}