version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
  otel-collector:
    image: otel/opentelemetry-collector:0.90.1
    container_name: otel-collector
    volumes:
      - ./otelcollector/otelcollector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "8888:8888"
      - "8889:8889"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_OTEL_SAMPLING_PERCENTAGE=1.0
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_METRICS_ENABLED=true
      - OTEL_SERVICE_NAME=keycloak
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - JAVA_OPTS_APPEND=-javaagent:/tmp/opentelemetry-javaagent.jar
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "9901:9901"
      - "51051:51051"
    command: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster", "front-proxy"]
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
  opa:
    image: openpolicyagent/opa:latest-envoy
    ports:
      - "9191:9191"
      - "8181:8181"
    command:
      - run
      - --server
      - --config-file=/opa.yaml
      - --log-level=debug
      - /policy.rego
    volumes:
      - ./opa/policy.rego:/policy.rego
      - ./opa/opa.yaml:/opa.yaml