apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: igw-route
  namespace: istio-ingress
spec:
  parentRefs:
    - kind: Gateway
      name: external-http
      namespace: gw-infra
  rules:
    - backendRefs:
        - name: istio-ingressgateway
          port: 8080
